version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm cypress run --record --key d716a36b-2d46-4b20-8759-789485c02d55 --spec "cypress/integration/casaToro/vw_modelos_test.js"
workflows:
    build-and-test:
      jobs:
        - build-and-test
